export default {
  extends: ["stylelint-config-standard"],
  defaultSeverity: "error",
  maxWarnings: 0,
  referenceFiles: ["src/styles/tokens.css"],
  reportDescriptionlessDisables: true,
  reportInvalidScopeDisables: true,
  reportNeedlessDisables: true,
  reportUnscopedDisables: true,
  rules: {
    "at-rule-disallowed-list": ["import"],
    "color-no-hex": true,
    "color-named": "never",
    "custom-property-pattern": "^[a-z][a-z0-9]*(?:-[a-z0-9]+)*$",
    "declaration-no-important": true,
    "declaration-property-value-no-unknown": true,
    "function-disallowed-list": ["rgb", "rgba", "hsl", "hsla"],
    "function-url-scheme-disallowed-list": ["http", "https"],
    "no-descending-specificity": true,
    "no-unknown-custom-properties": true,
    "property-no-vendor-prefix": [true, { ignoreProperties: ["-webkit-user-select"] }],
    "selector-class-pattern": "^[a-z][a-z0-9]*(?:-[a-z0-9]+)*$",
    "selector-max-class": 3,
    "selector-max-combinators": 2,
    "selector-max-id": 0,
    "selector-max-specificity": "0,3,1",
    "selector-no-qualifying-type": true,
  },
  overrides: [
    {
      files: ["src/styles/tokens.css"],
      rules: {
        "color-no-hex": null,
        "color-named": null,
        "function-disallowed-list": null,
      },
    },
  ],
};
