import { black, srgbToLinear } from "./color";
import { createPalette } from "./render";
import type {
  ColorRecipeMap,
  CssTokenName,
  GlowRecipeMap,
  Material,
  PaletteValidationConfig,
  Scene,
  ShadowRecipeMap,
  TokenRecipe,
} from "./types";

function emissiveMaterial(color: string, roughness = 1): Material {
  return Object.freeze({
    albedo: black,
    metalness: 0,
    roughness,
    specularIntensity: 0,
    emissivity: srgbToLinear(color),
    translucency: 0,
  });
}

function surfaceMaterial(color: string, roughness: number, specularIntensity: number): Material {
  return Object.freeze({
    albedo: srgbToLinear(color),
    metalness: 0,
    roughness,
    specularIntensity,
    emissivity: black,
    translucency: 0,
  });
}

function translucentMaterial(color: string): Material {
  return Object.freeze({
    albedo: black,
    metalness: 0,
    roughness: 1,
    specularIntensity: 0,
    emissivity: srgbToLinear(color),
    translucency: 0,
  });
}

function recipe(material: string, elevation: number, occlusion: number, rim: number, alpha?: number): TokenRecipe {
  return alpha === undefined
    ? Object.freeze({ material, elevation, occlusion, rim })
    : Object.freeze({ material, elevation, occlusion, rim, alpha });
}

export const defaultScene: Scene = Object.freeze({
  key: Object.freeze({
    color: srgbToLinear("#f0f6ff"),
    intensity: 0.32,
  }),
  ambient: Object.freeze({
    color: srgbToLinear("#0b1420"),
    intensity: 0.68,
  }),
  localIlluminants: Object.freeze({}),
  exposure: 1,
  adaptationWhitePoint: srgbToLinear("#f0f6ff"),
  tintStrength: 0.35,
  toneResponse: Object.freeze({
    blackPoint: 0.002,
    midGray: 0.18,
    whitePoint: 1,
    contrast: 1.04,
    toe: Object.freeze({
      length: 0.12,
      strength: 0.55,
    }),
    shoulder: Object.freeze({
      start: 0.82,
      strength: 0.35,
    }),
  }),
  chromaResponse: Object.freeze({
    byLuminance: Object.freeze([
      Object.freeze({ luminance: 0, chromaScale: 0.62 }),
      Object.freeze({ luminance: 0.05, chromaScale: 0.72 }),
      Object.freeze({ luminance: 0.18, chromaScale: 0.92 }),
      Object.freeze({ luminance: 0.65, chromaScale: 1 }),
      Object.freeze({ luminance: 1, chromaScale: 0.96 }),
    ]),
  }),
});

export const defaultMaterials = Object.freeze({
  neutral: surfaceMaterial("#284868", 0.85, 0.8),
  "neutral-edge": surfaceMaterial("#0058b0", 0.85, 0.8),
  "text-primary": emissiveMaterial("#f3ffff"),
  "text-muted": emissiveMaterial("#95aee0"),
  "text-nav-muted": emissiveMaterial("#7599c5"),
  "text-nav-parent": emissiveMaterial("#b3d9ff"),
  "icon-muted": emissiveMaterial("#5f7baa"),
  "accent-text": emissiveMaterial("#fcffff", 0.72),
  "accent-hover": emissiveMaterial("#ffffff", 0.72),
  "accent-surface": surfaceMaterial("#284470", 0.72, 0.2),
  "accent-edge": surfaceMaterial("#0060c0", 0.72, 2),
  "danger-text": emissiveMaterial("#ff9698", 0.78),
  "danger-surface": surfaceMaterial("#701f1f", 0.88, 0.05),
  "danger-edge": surfaceMaterial("#ff3030", 0.82, 0.2),
  "post-tag": emissiveMaterial("#bd7220"),
  "leaderboard-gold": emissiveMaterial("#e9d681"),
  "leaderboard-silver": emissiveMaterial("#d4dee3"),
  "leaderboard-bronze": emissiveMaterial("#da9a5e"),
  overlay: translucentMaterial("#04080c"),
  "output-title-dim": emissiveMaterial("#a2baed"),
  spotlight: translucentMaterial("#e8f2ff"),
  "code-surface": surfaceMaterial("#30bc90", 0.82, 0.08),
  "code-border": emissiveMaterial("#2e7761"),
  "code-accent": emissiveMaterial("#3adac2"),
  "code-attribute": emissiveMaterial("#79d0d0"),
  "code-comment": emissiveMaterial("#69aea1"),
  "code-keyword": emissiveMaterial("#88e0ff"),
  "code-literal": emissiveMaterial("#f8ce6f"),
  "code-meta": emissiveMaterial("#ffa0a6"),
  "code-string": emissiveMaterial("#c1ef94"),
  "code-title": emissiveMaterial("#dabcff"),
});

export const arcadeTokenRecipes = Object.freeze({
  "--color-page": recipe("neutral", -2, 0.8, 0),
  "--color-surface": recipe("neutral", -1.6, 0.35, 0),
  "--color-surface-subtle": recipe("neutral", -1.2, 0.25, 0.01),
  "--color-surface-hover": recipe("neutral", -0.3, 0.2, 0.03),
  "--color-surface-muted": recipe("neutral", 0.5, 0.12, 0.05),
  "--color-text": recipe("text-primary", 0, 0, 0),
  "--color-text-muted": recipe("text-muted", 0, 0, 0),
  "--color-text-nav-muted": recipe("text-nav-muted", 0, 0, 0),
  "--color-text-nav-active-parent": recipe("text-nav-parent", 0, 0, 0),
  "--color-icon-muted": recipe("icon-muted", 0, 0, 0),
  "--color-border": recipe("neutral-edge", -0.8, 0.1, 0.4),
  "--color-border-subtle": recipe("neutral-edge", -1.2, 0.2, 0.25),
  "--color-border-hover": recipe("neutral-edge", 1, 0.05, 1),
  "--color-accent": recipe("accent-text", 0, 0, 0),
  "--color-accent-hover": recipe("accent-hover", 0, 0, 0),
  "--color-accent-surface": recipe("accent-surface", 1.3, 0.2, 0.05),
  "--color-accent-surface-hover": recipe("accent-surface", 3.5, 0.1, 0.2),
  "--color-accent-badge-surface": recipe("accent-surface", 1.3, 0.2, 0.05),
  "--color-accent-border": recipe("accent-edge", 2, 0.2, 0.5),
  "--color-accent-border-hover": recipe("accent-edge", 2, 0.1, 0.7),
  "--color-accent-badge-border": recipe("accent-edge", 0, 0.2, 0.35),
  "--color-accent-action": recipe("accent-surface", 2.8, 0.1, 0.08),
  "--color-accent-action-hover": recipe("accent-surface", 3.5, 0.05, 0.4),
  "--color-accent-action-text": recipe("accent-hover", 0, 0, 0),
  "--color-danger": recipe("danger-text", 0, 0, 0),
  "--color-danger-surface": recipe("danger-surface", -0.8, 0.7, 0.03),
  "--color-danger-border": recipe("danger-edge", -0.3, 0, 0.3),
  "--color-danger-border-hover": recipe("danger-edge", 3.2, 0, 0.3),
  "--color-post-tag": recipe("post-tag", 0, 0, 0),
  "--color-leaderboard-gold": recipe("leaderboard-gold", 0, 0, 0),
  "--color-leaderboard-silver": recipe("leaderboard-silver", 0, 0, 0),
  "--color-leaderboard-bronze": recipe("leaderboard-bronze", 0, 0, 0),
  "--color-header": recipe("neutral", -1.9, 0.72, 0),
  "--color-header-muted": recipe("text-muted", 0, 0, 0),
  "--color-inverse-text": recipe("text-primary", 0, 0, 0),
  "--color-overlay": recipe("overlay", 0, 0, 0, 0.64),
  "--color-toast": recipe("neutral", -2.02, 0.88, 0),
  "--color-output-item-title-dim": recipe("output-title-dim", 0, 0, 0),
  "--color-feed-spotlight": recipe("spotlight", 0, 0, 0, 0.08),
  "--color-feed-spotlight-transparent": recipe("spotlight", 0, 0, 0, 0),
  "--color-code-surface": recipe("code-surface", -0.45, 0.62, 0.02),
  "--color-code-border": recipe("code-border", 0, 0, 0),
  "--color-code-accent": recipe("code-accent", 0, 0, 0),
  "--color-code-fade-start": recipe("code-surface", -0.45, 0.62, 0.02, 0),
  "--color-code-attribute": recipe("code-attribute", 0, 0, 0),
  "--color-code-comment": recipe("code-comment", 0, 0, 0),
  "--color-code-keyword": recipe("code-keyword", 0, 0, 0),
  "--color-code-literal": recipe("code-literal", 0, 0, 0),
  "--color-code-meta": recipe("code-meta", 0, 0, 0),
  "--color-code-string": recipe("code-string", 0, 0, 0),
  "--color-code-title": recipe("code-title", 0, 0, 0),
} satisfies ColorRecipeMap);

export const arcadeShadowRecipes = Object.freeze({
  "--shadow-panel": Object.freeze({ elevation: 0, softness: 0, occlusion: 1, alpha: 0.4167 }),
  "--shadow-popover": Object.freeze({ elevation: 4, softness: 3, occlusion: 1, alpha: 0.45 }),
  "--shadow-modal": Object.freeze({ elevation: 8, softness: 10.3333, occlusion: 1, alpha: 0.58 }),
  "--shadow-toast": Object.freeze({ elevation: 2.6667, softness: 2.7778, occlusion: 1, alpha: 0.5294 }),
} satisfies ShadowRecipeMap);

export const arcadeGlowRecipes = Object.freeze({
  "--filter-leaderboard-gold-glow": Object.freeze({
    kind: "drop-shadow",
    color: srgbToLinear("#e7d17a"),
    offsetX: 0,
    offsetY: 0,
    blur: 3,
    alpha: 0.45,
  }),
  "--shadow-leaderboard-gold-text": Object.freeze({
    kind: "text-shadow",
    color: srgbToLinear("#e7d17a"),
    offsetX: 0,
    offsetY: 0,
    blur: 5,
    alpha: 0.38,
  }),
} satisfies GlowRecipeMap);

export const arcadeColorTargets = Object.freeze({
  "--color-page": "#060a10",
  "--color-surface": "#11151b",
  "--color-surface-subtle": "#171c24",
  "--color-surface-hover": "#202733",
  "--color-surface-muted": "#26303d",
  "--color-text": "#f0f4f8",
  "--color-text-muted": "#a3adba",
  "--color-text-nav-muted": "#8994a3",
  "--color-text-nav-active-parent": "#c6d0dc",
  "--color-icon-muted": "#707b8a",
  "--color-border": "#303947",
  "--color-border-subtle": "#242b35",
  "--color-border-hover": "#4a586b",
  "--color-accent": "#f0f6ff",
  "--color-accent-hover": "#ffffff",
  "--color-accent-surface": "#202936",
  "--color-accent-surface-hover": "#293443",
  "--color-accent-badge-surface": "#202936",
  "--color-accent-border": "#5a6a80",
  "--color-accent-border-hover": "#708298",
  "--color-accent-badge-border": "#465466",
  "--color-accent-action": "#26303d",
  "--color-accent-action-hover": "#303b4a",
  "--color-accent-action-text": "#ffffff",
  "--color-danger": "#ff9592",
  "--color-danger-surface": "#241515",
  "--color-danger-border": "#5a2a2a",
  "--color-danger-border-hover": "#8a3a38",
  "--color-post-tag": "#b87333",
  "--color-leaderboard-gold": "#e7d17a",
  "--color-leaderboard-silver": "#d6d6d6",
  "--color-leaderboard-bronze": "#d6985e",
  "--color-header": "#080c12",
  "--color-header-muted": "#a3adba",
  "--color-inverse-text": "#f0f4f8",
  "--color-overlay": "rgb(2 6 8 / 64%)",
  "--color-toast": "#05080d",
  "--color-output-item-title-dim": "#afb8c4",
  "--color-feed-spotlight": "rgb(232 242 255 / 8%)",
  "--color-feed-spotlight-transparent": "rgb(232 242 255 / 0%)",
  "--color-code-surface": "#2c4a3e",
  "--color-code-border": "#4d725f",
  "--color-code-accent": "#50d4b7",
  "--color-code-fade-start": "rgb(44 74 62 / 0%)",
  "--color-code-attribute": "#80cbc4",
  "--color-code-comment": "#8ea39b",
  "--color-code-keyword": "#8edcff",
  "--color-code-literal": "#f3c969",
  "--color-code-meta": "#ff9e9e",
  "--color-code-string": "#c3e88d",
  "--color-code-title": "#d9b8ff",
} satisfies Partial<Record<CssTokenName, string>>);

export const arcadeRequiredTokens = Object.freeze([
  "--color-page",
  "--color-surface",
  "--color-surface-subtle",
  "--color-surface-hover",
  "--color-surface-muted",
  "--color-text",
  "--color-text-muted",
  "--color-text-nav-muted",
  "--color-text-nav-active-parent",
  "--color-icon-muted",
  "--color-border",
  "--color-border-subtle",
  "--color-border-hover",
  "--color-accent",
  "--color-accent-hover",
  "--color-accent-surface",
  "--color-accent-surface-hover",
  "--color-accent-badge-surface",
  "--color-accent-border",
  "--color-accent-border-hover",
  "--color-accent-badge-border",
  "--color-accent-action",
  "--color-accent-action-hover",
  "--color-accent-action-text",
  "--color-danger",
  "--color-danger-surface",
  "--color-danger-border",
  "--color-danger-border-hover",
  "--color-post-tag",
  "--color-leaderboard-gold",
  "--color-leaderboard-silver",
  "--color-leaderboard-bronze",
  "--color-header",
  "--color-header-muted",
  "--color-inverse-text",
  "--color-overlay",
  "--color-toast",
  "--color-output-item-title-dim",
  "--color-feed-spotlight",
  "--color-feed-spotlight-transparent",
  "--color-code-surface",
  "--color-code-border",
  "--color-code-accent",
  "--color-code-fade-start",
  "--color-code-attribute",
  "--color-code-comment",
  "--color-code-keyword",
  "--color-code-literal",
  "--color-code-meta",
  "--color-code-string",
  "--color-code-title",
  "--shadow-panel",
  "--shadow-popover",
  "--shadow-modal",
  "--shadow-toast",
  "--filter-leaderboard-gold-glow",
  "--shadow-leaderboard-gold-text",
] satisfies CssTokenName[]);

export const arcadePaletteValidation: PaletteValidationConfig = Object.freeze({
  requiredTokens: arcadeRequiredTokens,
  targets: arcadeColorTargets,
  maximumTargetDistance: 0.045,
  contrast: Object.freeze([
    Object.freeze({ foreground: "--color-text", background: "--color-page", minimum: 7 }),
    Object.freeze({ foreground: "--color-text", background: "--color-surface", minimum: 7 }),
    Object.freeze({ foreground: "--color-text-muted", background: "--color-surface", minimum: 4.5 }),
    Object.freeze({ foreground: "--color-danger", background: "--color-surface", minimum: 4.5 }),
    Object.freeze({ foreground: "--color-accent", background: "--color-page", minimum: 3 }),
    Object.freeze({ foreground: "--color-accent", background: "--color-surface", minimum: 3 }),
  ]),
  distinction: Object.freeze([
    Object.freeze({ first: "--color-page", second: "--color-surface", minimumDistance: 0.025 }),
    Object.freeze({ first: "--color-surface", second: "--color-surface-subtle", minimumDistance: 0.018 }),
    Object.freeze({ first: "--color-surface-subtle", second: "--color-surface-hover", minimumDistance: 0.025 }),
    Object.freeze({ first: "--color-surface-hover", second: "--color-surface-muted", minimumDistance: 0.018 }),
    Object.freeze({ first: "--color-surface", second: "--color-accent-surface", minimumDistance: 0.03 }),
    Object.freeze({
      first: "--color-accent-surface",
      second: "--color-accent-surface-hover",
      minimumDistance: 0.025,
    }),
    Object.freeze({ first: "--color-border", second: "--color-accent-border", minimumDistance: 0.06 }),
  ]),
});

export function createArcadePalette(scene: Scene = defaultScene) {
  return createPalette({
    scene,
    materials: defaultMaterials,
    recipes: arcadeTokenRecipes,
    shadowRecipes: arcadeShadowRecipes,
    glowRecipes: arcadeGlowRecipes,
    validation: arcadePaletteValidation,
  });
}
